<?PHP
 session_start();
    include 'connect.php';
?>
<!DOCTYPE html>
<html>
<head>
    <title>Export HMO</title>
</head>
<body onload="submit()">
    <form method="post" id="export-form">
        <input type="hidden" value='export-to-excel' id='hidden-type' name='ExportType'/>
    </form>
    <?php
    date_default_timezone_set("Asia/Kuala_Lumpur");
    $printdate = date("Y-m-d H:i:s");
    $today = date("Y-m-d");
    $query9=mysqli_query($conn,"SELECT * FROM qpd_users where user='".$_SESSION['user']."'");
    $query10=mysqli_fetch_array($query9);
     echo "<b><h3>Printed/Generated by ".$query10[3]." </h3></b>";
     echo "<h5>".$printdate."</h5>";
    ?>
<table class="table table-hover table-striped">
      <thead>
        <tr>
          <th>Date/Time</th>
          <th>HMO</th>
          <th>Trans Type</th>
          <th>Trans No.</th>
          <th>Customer Name</th>
          <th>Company</th>
          <th>Age/Gender</th>
          <th>Contact No.</th>
          <th>LOE</th>
          <th>AN</th>
          <th>AC</th>
        </tr>
      </thead>
      <tbody>
      <?PHP
                    $query1 = mysqli_query($conn, "SELECT * FROM qpd_trans where status=0 AND bill LIKE 'Intellicare' OR bill LIKE 'Avega' AND status=0 OR bill LIKE 'Cocolife' AND status=0 OR bill LIKE 'Valucare' AND status=0 OR bill LIKE 'Eastwest' AND status=0 OR bill LIKE 'Maxicare' AND status=0 ");
                    while($query2 = mysqli_fetch_array($query1))
                    {
                         echo "<td>".strip_tags($query2[22])."</td>";
                          echo "<td>".strip_tags($query2[14])."</td>";
                          echo "<td>".strip_tags($query2[1])."</td>";
                          echo "<td>".strip_tags($query2[0])."</td>";
                          echo "<td>".strip_tags($query2[7]). " " .strip_tags($query2[5]). "</td>";
                          echo "<td>".strip_tags($query2[3])."</td>";
                          echo "<td>".strip_tags($query2[10]). "/" .strip_tags($query2[11])."</td>";
                          echo "<td>".strip_tags($query2[12])."</td>";
                          echo "<td>".strip_tags($query2[24])."</td>";
                          echo "<td>".strip_tags($query2[25])."</td>";
                          echo "<td>".strip_tags($query2[26])."</td>";
                          // echo "<td><a href='?delete&id=".$query2[0]."'>Delete</a></td>";
                          // echo "<td><a href='?edit&id=".$query2[0]."'>Edit</a></td>";
                        echo "</tr>";
                      }
                  ?>
                </tbody>
              </table>
                </body>
            </html>
<script type="text/javascript">
    function submit(){
        var submit=document.getElementById('export-form');
        submit.submit();
    }
</script>
<?PHP

if(isset($_POST["ExportType"])){
    switch($_POST["ExportType"]){
        case "export-to-excel" :
            // Submission from
            date_default_timezone_set("Asia/Kuala_Lumpur");
            $printdate = date("Y-m-d H:i:s");
            $today = date("Y-m-d");
            $filename="HMO (exported: ".$today.").xls";
            header("Content-Type: text/plain");       
            header("Content-Type: application/vnd.ms-excel");
            header("Content-Disposition: attachment; filename=\"$filename\"");
            ExportFile($query2);
            //$_POST["ExportType"] = '';
            exit();
        default :
            die("Unknown action : ".$_POST["action"]);
            break;
    }
}
function ExportFile($records) {
    $heading = false;
        foreach($records as $row){
            if(!$heading) {
              // display field/column names as a first row
              echo implode("\t", array_keys($row)) . "\n";
              $heading = true;
            }
            echo implode("\t", array_values($row)) . "\n";
        }
        exit;
}
?>
