<?PHP
 session_start();
    include 'connect.php';
?>
<!DOCTYPE html>
<html>
<head>
    <title>Export Transaction Lists</title>
</head>
<body onload="submit()">
    <form method="post" id="export-form">
        <input type="hidden" value='export-to-excel' id='hidden-type' name='ExportType'/>
    </form>
    <?php
    date_default_timezone_set("Asia/Kuala_Lumpur");
    $printdate = date("Y-m-d H:i:s");
    $today = date("Y-m-d");
    $query9=mysqli_query($conn,"SELECT * FROM qpd_users where user='".$_SESSION['user']."'");
    $query10=mysqli_fetch_array($query9);
     echo "<b><h3>Printed/Generated by ".$query10[3]." </h3></b>";
     echo "<h5>".$printdate."</h5>";
    ?>
<table class="table table-hover table-striped" id='transtable'>
      <thead>
        <tr>
          <th>Date/Time</th>
          <th>Cashier</th>
          <th>Trans No.</th>
          <th>Trans Type</th>
          <th>Customer Name</th>
          <th>Company</th>
          <th>Age/Gender</th>
          <th>Contact No</th>
          <th>Package</th>
          <th>Price Total</th>
          <th>Cash</th>
          <th>Change</th>
        </tr>
      </thead>
      <tbody>
        <?PHP         
              $query1 = mysqli_query($conn, "SELECT * FROM qpd_trans where status=0 order by id asc,id asc");
              while($query2 = mysqli_fetch_array($query1))
              {
                echo "<tr>";
                  echo "<td>".strip_tags($query2[22])."</td>";
                  echo "<td>".strip_tags($query2[2])."</td>";
                    echo "<td>".strip_tags($query2[0])."</td>";
                    echo "<td>".strip_tags($query2[1])."</td>";
                    echo "<td>".strip_tags($query2[7]). "," .strip_tags($query2[5]). " " .strip_tags($query2[6]). "</td>";
                    echo "<td>".strip_tags($query2[3])."</td>";
                    echo "<td>".strip_tags($query2[10]). "/" .strip_tags($query2[11]). "</td>";
                    echo "<td>".strip_tags($query2[12])."</td>";
                    echo "<td>";
                                $prod=$query2[17];
                                $ctr=1;
                                $arr=0;
                                $perprod=0;
                                $num=strlen($prod)-1;
                                for($a=0;$a<$num;$a++){
                                    $qty[$a]=0;
                                  }
                      if($num==1){
                      $product[$arr]=$prod[$ctr];
                      $query3=mysqli_query($conn,"SELECT * FROM qpd_package WHERE id=".$product[$arr]);
                      $query4=mysqli_fetch_array($query3);
                      echo $query4[1]. "(" .$query4[3]. ") - " .$query4[2]. "<br>" ; 
                      
                  }
                  while($ctr<$num){
                      if($prod[$ctr]!= ''){
                          if($prod[$ctr+1]==' '){
                                  $product[$arr]=$prod[$ctr];
                                  $query3=mysqli_query($conn,"SELECT * FROM qpd_package WHERE id=".$product[$arr]);
                                  $query4=mysqli_fetch_array($query3);
                                   echo $query4[1]. "(" .$query4[3]. ") - " .$query4[2]. "<br>" ; 
                          }
                          else{
                                  $product[$arr]=$prod[$ctr].$prod[$ctr+1];
                                  $ctr++;
                                  $query3=mysqli_query($conn,"SELECT * FROM qpd_package WHERE id=".$product[$arr]);
                                  $query4=mysqli_fetch_array($query3);
                                   echo $query4[1]. "(" .$query4[3]. ") - " .$query4[2]. "<br>" ; 
                              }
                          }
                      $ctr++;
                      if($ctr==$num){
                              $product[$arr]=$prod[$ctr];
                              $query3=mysqli_query($conn,"SELECT * FROM qpd_package WHERE id=".$product[$arr]);
                              $query4=mysqli_fetch_array($query3);
                               echo $query4[1]. "(" .$query4[3]. ") - " .$query4[2]. "<br>" ;  
                          }
                       }
                "</td>";
                    echo "<td>".strip_tags($query2[19])."</td>";
                    echo "<td>".strip_tags($query2[20])."</td>";
                    echo "<td>".strip_tags($query2[21])."</td>";
                  //echo "<td><a href='?reprint&id=".$query2[0]."'>Reprint Receipt</a></td>";
                 //echo "<td><a href='?edit&id=".$query2[0]."'>Edit</a></td>";
                echo "</tr>";
              }
         ?>
  </tbody>
  </table>
                </body>
            </html>
<script type="text/javascript">
    function submit(){
        var submit=document.getElementById('export-form');
        submit.submit();
    }
</script>
<?PHP

if(isset($_POST["ExportType"])){
    switch($_POST["ExportType"]){
        case "export-to-excel" :
            // Submission from
            date_default_timezone_set("Asia/Kuala_Lumpur");
            $printdate = date("Y-m-d H:i:s");
            $today = date("Y-m-d");
            $filename="Transaction List (exported: ".$today.").xls";
            header("Content-Type: text/plain");       
            header("Content-Type: application/vnd.ms-excel");
            header("Content-Disposition: attachment; filename=\"$filename\"");
            ExportFile($query2);
            //$_POST["ExportType"] = '';
            exit();
        default :
            die("Unknown action : ".$_POST["action"]);
            break;
    }
}
function ExportFile($records) {
    $heading = false;
        foreach($records as $row){
            if(!$heading) {
              // display field/column names as a first row
              echo implode("\t", array_keys($row)) . "\n";
              $heading = true;
            }
            echo implode("\t", array_values($row)) . "\n";
        }
        exit;
}
?>
