<?PHP
 session_start();
    include 'connect.php';
?>
<!DOCTYPE html>
<html>
<head>
    <title>Export Sales for Today</title>
</head>
<body onload="submit()">
    <form method="post" id="export-form">
        <input type="hidden" value='export-to-excel' id='hidden-type' name='ExportType'/>
    </form>
    <?php
    date_default_timezone_set("Asia/Kuala_Lumpur");
    $printdate = date("Y-m-d H:i:s");
    $today = date("Y-m-d");
    $query9=mysqli_query($conn,"SELECT * FROM qpd_users where user='".$_SESSION['user']."'");
    $query10=mysqli_fetch_array($query9);
     echo "<h5> Report from " .$_GET['SD']. " to " .$_GET['ED']. "</h5>";
     echo "<b><h3>Printed/Generated by ".$query10[3]." </h3></b>";
     echo "<h5>".$printdate."</h5>";
    ?>
<table class="table table-striped table-condensed table2">
                        <thead>
                            <tr>
                                <th>Package Order<br>Id</th>
                                <th>Cashier</th>
                                <th>Packages Availed</th>
                                <th>Trans Type</th>
                                <th>Total</th>
                                <th>Cash</th>
                                <th>Change</th>
                                <th>Date</th>
                            </tr>
                        </thead>
 <?php
    date_default_timezone_set("Asia/Kuala_Lumpur");
    $printdate = date("Y-m-d H:i:s");
    $today = date("Y-m-d");
    $SD = date("Y-m-d", strtotime($_GET['SD']));
    $ED = date("Y-m-d", strtotime('+1 day', strtotime($_GET['ED'])));
    //echo "<b><h3>Sales from ".$SD." to ".$_GET['ED']." </h3></b>";
    $query1=mysqli_query($conn, "SELECT * FROM qpd_trans WHERE date >= '$SD' AND date <= '$ED' AND packid!='' AND status=0 ");
                            while($query2=mysqli_fetch_array($query1)){
                                $prod=$query2[17];
                                $ctr=1;
                                $arr=0;
                                $num=strlen($prod)-1;
                                echo "<tr>";
                                    echo "<td>".$query2[0]."</td>";
                                    echo "<td>".$query2[2]."</td>";
                                    echo "<td class='ordertd'>";
                                    if($num==1){
                                        $product[$arr]=$prod[$ctr];
                                        $query3=mysqli_query($conn,"SELECT * FROM qpd_package WHERE id=".$product[$arr]);
                                        $query4=mysqli_fetch_array($query3);
                                        echo "Package: ".$query4[1]. "(" .$query4[3]. ")<span class='' style='float:right;'></span>"; 
                                        echo "<br>Price: ".$query4[2]."<br>";
                                        // echo $query4[2]."<span class='' style='float:right;'>";
                                        // echo $query4[4]."</span><br>";
                                    }
                                    while($ctr<$num){
                                        if($prod[$ctr]!=' '){
                                            if($prod[$ctr+1]==' '){
                                                $product[$arr]=$prod[$ctr];
                                                $query3=mysqli_query($conn,"SELECT * FROM qpd_package WHERE id=".$product[$arr]);
                                                $query4=mysqli_fetch_array($query3);
                                                echo "Package: ".$query4[1]. "(" .$query4[3]. ")<span class='' style='float:right;'></span>"; 
                                                echo "<br>Price: ".$query4[2]."<br>";
                                            }
                                            else{
                                                $product[$arr]=$prod[$ctr].$prod[$ctr+1];
                                                $ctr++;
                                                $query3=mysqli_query($conn,"SELECT * FROM qpd_package WHERE id=".$product[$arr]);
                                                $query4=mysqli_fetch_array($query3);
                                                echo "Package: ".$query4[1]. "(" .$query4[3]. ")<span class='' style='float:right;'></span>"; 
                                                echo "<br>Price: ".$query4[2]."<br>";
                                            }
                                        }
                                        $ctr++;
                                        if($ctr==$num){
                                            $product[$arr]=$prod[$ctr];
                                            $query3=mysqli_query($conn,"SELECT * FROM qpd_package WHERE id=".$product[$arr]);
                                            $query4=mysqli_fetch_array($query3);
                                            echo "Package: ".$query4[1]. "(" .$query4[3]. ")<span class='' style='float:right;'></span>"; 
                                            echo "<br>Price: ".$query4[2]."<br>";
                                        }
                                    }
                                    echo "</td>"; 
                                    echo "<td>".$query2[1]."</td>";
                                    echo "<td>".$query2[19]."</td>";
                                    echo "<td>".$query2[20]."</td>";
                                    echo "<td>".$query2[21]."</td>";
                                    echo "<td>".$query2[22]."</td>";
                                    // echo "<td>".$query2[7]."</td>";
                                    // echo "<td>".$query2[8]."</td>";
                                    // echo "<td>".$query2[9]."</td>";
                                    // echo "<td>".$void."</td>";
                                echo "</tr>";
                            }
                        ?>
                         </tbody>
                    </table>
                </body>
            </html>
<script type="text/javascript">
    function submit(){
        var submit=document.getElementById('export-form');
        submit.submit();
    }
</script>
<?PHP

if(isset($_POST["ExportType"])){
    switch($_POST["ExportType"]){
        case "export-to-excel" :
            // Submission from
        	date_default_timezone_set("Asia/Kuala_Lumpur");
		    $printdate = date("Y-m-d H:i:s");
		    $today = date("Y-m-d");
            $filename="Sales Report from ".$_GET['SD']. " to " .$_GET['ED'].".xls";
            header("Content-Type: text/plain");       
            header("Content-Type: application/vnd.ms-excel");
            header("Content-Disposition: attachment; filename=\"$filename\"");
            ExportFile($query2);
            //$_POST["ExportType"] = '';
            exit();
        default :
            die("Unknown action : ".$_POST["action"]);
            break;
    }
}
function ExportFile($records) {
    $heading = false;
        foreach($records as $row){
            if(!$heading) {
              // display field/column names as a first row
              echo implode("\t", array_keys($row)) . "\n";
              $heading = true;
            }
            echo implode("\t", array_values($row)) . "\n";
        }
        exit;
}
?>
